<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250624130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create subscriptions table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE subscriptions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, name VARCHAR(255) NOT NULL, amount NUMERIC(10, 2) NOT NULL, billing_cycle VARCHAR(255) NOT NULL, category VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_subscriptions_user_id ON subscriptions (user_id)');
        $this->addSql('ALTER TABLE subscriptions ADD CONSTRAINT FK_subscriptions_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE subscriptions DROP CONSTRAINT FK_subscriptions_user_id');
        $this->addSql('DROP TABLE subscriptions');
    }
}
